### ISSUE TITLE
Update Wordpress Version

### ISSUE THREAD

**Issue by Ethab83** [Ethab83/MundoPrints-Visiting.Cards#12]
### Description

[Update wordpress version](https://www.mundoprints.in/wp-admin/update-core.php) so that we can add more integrations and stay up-to-date with the newest security features.

> [!WARNING]
> This will put the site in maintenance mode. As soon as the updates are complete, this mode will be deactivated.

> [!IMPORTANT]
> Before updating, please [back up your database and files](https://wordpress.org/documentation/article/wordpress-backups/). For help with updates, visit the [Updating WordPress](https://wordpress.org/documentation/article/updating-wordpress/) documentation page.

**Comment by slashback00** [comment]
I have successfully updated the WordPress version as per the task description.
